export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REM_ITEM_FROM_CART = 'REM_ITEM_FROM_CART';
export const SAVE_CART_TO_STORAGE = 'SAVE_CART_TO_STORAGE';
export const LOAD_CART_FROM_STORAGE = 'LOAD_CART_FROM_STORAGE';
